trigger:
- '*'

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET SDK 6.x'
  inputs:
    packageType: sdk
    version: '6.x'

- task: NodeTool@0
  displayName: 'Use Node.js 20.x'
  inputs:
    versionSpec: '20.x'

- task: Npm@1
  displayName: 'Run npm install2'
  inputs:
    verbose: false

- script: 'npx sass Tailspin.SpaceGame.Web\wwwroot --output Tailspin.SpaceGame.Web\wwwroot'
  displayName: 'Compile Sass assets (Windows)'

- task: Gulp@1
  displayName: 'Run gulp tasks'

- script: 'echo %BUILD_DEFINITIONNAME%, %BUILD_BUILDID%, %BUILD_BUILDNUMBER% > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: Tailspin.SpaceGame.Web\wwwroot

- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Build the project - Release'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration Release'
    projects: '**/*.csproj'
